services:
  chromadb:
      image: chromadb/chroma
      ports:
        - 8000:8000
      volumes:
        # Be aware that indexed data are located in "/chroma/chroma/"
        # Default configuration for persist_directory in chromadb/config.py
        # Read more about deployments: https://docs.trychroma.com/deployment
        - ./chroma-data:/chroma/chroma
      environment:
        - IS_PERSISTENT=TRUE
